### ISSUE TITLE
Npm run deploy returns Error: Could not set up basepath mapping.

### ISSUE THREAD

**Issue by JimiPedros** [adnanrahic/serverless-side-rendering-react-next#2]
steps:
1. clone repo
2. install dependencies
3. run deploy script

error message:
```
Error: Could not set up basepath mapping. Try running sls create_domain first.
Error: Error: 'reactssr.yourdomain.com' could not be found in API Gateway.
NotFoundException: Invalid domain name identifier specified

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
```

**Comment by JimiPedros** [comment]
I've manage to fix this issue by removing the package  `serverless-domain-manager` and updating the plugins list. 

My serverless.yml now looks like this:

```
service: ssr-react-next

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${self:custom.secrets.NODE_ENV}
  region: ${self:custom.secrets.REGION}
  environment:
    NODE_ENV: ${self:custom.secrets.NODE_ENV}

functions:
  server:
    handler: index.server
    events:
      - http: ANY /
      - http: ANY /{proxy+}

plugins:
  - serverless-apigw-binary

custom:
  secrets: ${file(secrets.json)}
  apigwBinary:
    types:
      - '*/*'
        # customDomain:
        # domainName: ${self:custom.secrets.DOMAIN}
        # basePath: ''
        # stage: ${self:custom.secrets.NODE_ENV}
        # createRoute53Record: true
    # endpointType: 'regional'
    # if the ACM certificate is created in a region except for `'us-east-1'` you need `endpointType: 'regional'`
```

Now I can deploy without configuring a custom domain. Hope this helps some people
